name: Feature Request
description: Suggest an idea or enhancement
title: "[FEAT]: "
labels: ["enhancement", "triage"]
projects: []
assignees:
  - dirtycajunrice
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem? 
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would love to be able to [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried to do [...] but it doesn't accomplish [...]
    validations:
      required: true
  - type: dropdown
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you running?
      options:
        - v1.8.0-dev
        - v1.7.0
        - v1.6.0
        - v1.5.0
        - v1.4.0
    validations:
      required: true
  - type: dropdown
    id: plugin-source
    attributes:
      label: Plugin Source
      description: Where get you get the plugin from?
      options:
        - Fab Marketplace
        - Github
    validations:
      required: true
  - type: dropdown
    id: unreal-engine-version
    attributes:
      label: Unreal Engine Version
      description: What version of Unreal Engine are you running?
      options:
        - 5.5
        - 5.4
        - 5.3
        - 5.2
        - 5.1
        - 5.0
    validations:
      required: true
  - type: dropdown
    id: unreal-engine-source
    attributes:
      label: Unreal Engine Source
      description: What source did you install unreal engine from?
      options:
        - Epic Games Launcher
        - GitHub
    validations:
      required: true
  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: What type of project are you developing with?
      options:
        - Blueprint-Only
        - C++
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/thirdweb-dev/unreal-sdk/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true